language: node_js

before_install:
    - npm install -g npm
    - npm install -g bower
    - npm install -g karma-cli

install:
    - npm install
    - bower install

before_script:
    - gulp constant:generate -env=testing
    - gulp template:generate -env=testing

script:
    - karma start
