language: node_js

before_install:
    - npm install -g npm
    - npm install -g bower

install:
    - npm install
    - bower install

script:
    - npm test

after_script:
    - cat ./test/coverage/lcov.info | ./node_modules/.bin/coveralls
