language: node_js

before_install:
    - npm install -g npm
    - npm install -g bower

install:
    - npm install
    - bower install

script:
    - npm test

after_script:
    - ./node_modules/.bin/codeclimate < ./test/coverage/lcov.info
